# Generated by Django 4.1.7 on 2024-01-05 09:19

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=15, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=15, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.MaxLengthValidator(13, message="Telefon raqam noto'g'ri"), django.core.validators.MinLengthValidator(9, message="Telefon raqam noto'g'ri")])),
                ('status', models.CharField(choices=[('lid', 'lid'), ('active', 'active'), ('finished', 'finished')], default='lid', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(upload_to=main.models.change_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif'], message='Ruxsat berilmagan format')]),
        ),
    ]
