# Generated by Django 4.1.7 on 2024-01-05 10:46

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resident_alter_admin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(upload_to=main.models.change_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'gif'], message='Ruxsat berilmagan format')]),
        ),
    ]
