# Generated by Django 5.0.1 on 2024-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resident_balans_resident_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='position',
            field=models.CharField(choices=[('admin', 'admin'), ('cashier', 'cashier')], default='admin', max_length=15),
        ),
    ]
